name: CI/CD Workflow 

on: 
  push:
    branches: 
      - main 

on: 
  pull_request: 

on: 
  workflow_dispatch: 

----
jobs: 
  testing-env:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2 
      - name: Run Test 
        run: npm test 
      - name: NodeJS Setup 
        uses: actions/setup-node@v2
        with: 
          node-version: '14'
----
env: 
  NODE_ENV: production 
  AWS_REGION: ap-southeast-1

secrets.AWS_ACCESS_KEY_ID 

startegy: 
  matrix: 
    os: [ubuntu-latest, windows-latest]
    node: [12, 14]

  
jobs: 
  test: 
    runs-on: ubuntu-latest 
    steps:  
      - name: Run Test 
        run: npm test 
  
  build: 
    runs-on: ubuntu-latest 
    needs: test 

  
 if: github.ref == 'refs/heads/main'

 outputs: echo DockerImae 